# Generated by Django 5.1.3 on 2024-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_servico_cliente_cliente_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
